# Rename old log file if it exists
[[ -f ~/.xsession-errors ]] && mv ~/.xsession-errors ~/.xsession-errors.old
# Redirect stdout/err from virtual console to log file
exec > ~/.xsession-errors 2>&1

# Merge .Xresources
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# Set keyboard layout
setxkbmap -layout it -variant nodeadkeys
# Remap caps lock to Windows key when held
xmodmap -e 'keysym Caps_Lock = Hyper_L'
xmodmap -e 'keycode any = Caps_Lock'
xmodmap -e 'remove lock = Hyper_L'
xmodmap -e 'add lock = Caps_Lock'
xcape -e 'Hyper_L=Caps_Lock'

# Set default cursor to left pointer instead of cross
xsetroot -cursor_name left_ptr
{%@@ if profile == "laptop" @@%}
# Hide mouse cursor when inactive (unclutter-xfixes)
unclutter --fork
{%@@ endif @@%}

{%@@ if profile == "home-desktop" @@%}
# Set HDMI-1 screen to primary
xrandr --output HDMI-1 --primary

# Status bar volume setup (see ~/bin/volume)
# Create a volume file if it doesn't exist
volume init
# Write the initial value (in the background because this may be slow before X is started)
volume &
{%@@ endif @@%}

# Activate numlock
numlockx &

# Start background programs
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
       --expand true --width 3 --transparent true --tint 0x000000 --height 16 \
{%@@ if profile == "home-desktop" @@%}
       --monitor primary &
{%@@ else @@%}
       &
{%@@ endif @@%}
dunst & # Notification server
redshift-gtk &
dropbox &
emacs --daemon &

# Tell Java that xmonad is a non-reparenting window manager
export _JAVA_AWT_WM_NONREPARENTING=1

exec xmonad
