#!/usr/bin/env sh

# Rename old log file if it exists
[ -f ~/.xsession-errors ] && mv ~/.xsession-errors ~/.xsession-errors.old
# Redirect stdout/err from virtual console to log file
exec > ~/.xsession-errors 2>&1

# Merge .Xresources
[ -f ~/.Xresources ] && xrdb -merge -I"$HOME" ~/.Xresources

# Set keyboard layout
setxkbmap -layout it -variant nodeadkeys
# Set compose key
setxkbmap -option compose:prsc
# Remap caps lock to Windows key when held
xmodmap -e 'keysym Caps_Lock = Hyper_L'
xmodmap -e 'keycode any = Caps_Lock'
xmodmap -e 'remove lock = Hyper_L'
xmodmap -e 'add lock = Caps_Lock'
xcape -e 'Hyper_L=Caps_Lock'

# Set default cursor to left pointer instead of cross
xsetroot -cursor_name left_ptr
{%@@ if profile == "laptop" @@%}
# Hide mouse cursor when inactive (unclutter-xfixes)
unclutter --fork
{%@@ endif @@%}

{%@@ if profile == "home-desktop" @@%}
# Set HDMI-1 screen to primary
xrandr --output HDMI-1 --primary
{%@@ endif @@%}

# Source system-level X initialization scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

{%@@ if profile == "home-desktop" @@%}
# Status bar volume setup (see ~/.local/bin/volume)
# Create a volume file if it doesn't exist
volume init
# Write the initial value (in the background because this may be slow before X is started)
volume &
{%@@ endif @@%}

# Activate numlock
numlockx &

# Start background programs
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
       --expand true --width 3 --transparent true --tint 0x000000 --height 16 \
{%@@ if profile == "home-desktop" @@%}
       --monitor primary \
{%@@ endif @@%}
       &
dunst & # Notification server
redshift-gtk &
dropbox &
emacs --fg-daemon &

{%@@ if profile == "home-desktop" @@%}
# Shows desktop notifications from the restic systemd service
restic-notifier &
{%@@ endif @@%}

# Tell Java that xmonad is a non-reparenting window manager
export _JAVA_AWT_WM_NONREPARENTING=1

# Note that running the window manager as a child process instead of using exec
# only works if the WM doesn't fork to background (xmonad doesn't, but other
# WMs might)
xmonad

# Terminate background processes, which would otherwise stay running after logging out
#
# The `jobs` command lists not only running and stopped jobs, but also all jobs
# whose status has changed since it was last reported by the shell. Therefore,
# some of the PIDs returned by `jobs` may correspond to already-terminated
# processes, thus making the kill command produce some annoying error messages,
# such as:
#
#   kill: sending signal to 7899 failed: No such process
#
# The `-r` argument, which limits the output to running jobs, is available in
# bash but not in POSIX sh, so it technically shouldn't be used here, because
# this script is run with plain sh (even though sh is often emulated by bash).
# One solution would be to simply suppress `kill`'s stderr, but this might hide
# some actually important error messages. Instead, `jobs` is invoked twice,
# because, at least with bash, those jobs whose status has changed seem to be
# reported just once by the first invocation (which, due to the lack of the
# `-p` argument, displays job statuses as well as other information). Then, the
# second invocation (done with `-p` to print a list of PIDs) should hopefully
# only return running jobs and stopped jobs (i.e., those jobs that correspond
# to still-existing processes). This is not actually guaranteed to work,
# because some jobs could theoretically end between the two invocations of
# `jobs`, but it should eliminate annoying error messages in most cases without
# ever suppressing any important ones.
jobs > /dev/null
jobs -p | xargs --no-run-if-empty kill
wait
