config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  home-desktop:
    dotfiles:
    - f_xinitrc
    - f_xresources
  laptop:
    dotfiles:
    - f_xinitrc
    - f_xresources
