config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_fish_functions:
    dst: ~/.config/fish/functions
    link: true
    src: config/fish/functions
  f_config.fish:
    dst: ~/.config/fish/config.fish
    src: config/fish/config.fish
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    link: true
    src: config/nvim/init.vim
  f_profile:
    dst: ~/.profile
    src: profile
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  home-desktop:
    dotfiles:
    - d_fish_functions
    - f_config.fish
    - f_dunstrc
    - f_init.vim
    - f_profile
    - f_xinitrc
    - f_xresources
  laptop:
    dotfiles:
    - d_fish_functions
    - f_config.fish
    - f_dunstrc
    - f_init.vim
    - f_profile
    - f_xinitrc
    - f_xresources
