config:
  backup: true
  create: true
  dotpath: dotfiles
  minversion: 1.10.0
  diff_command: git diff --no-index --color=always -- {0} {1}
dotfiles:
  d_fish_functions_linux:
    src: config/fish/functions/linux
    dst: ~/.config/fish/functions
    link: absolute
  d_fish_functions_mac:
    src: config/fish/functions/mac
    dst: ~/.config/fish/functions
    link: absolute
  d_spacemacs.d:
    src: spacemacs.d
    dst: ~/.spacemacs.d
    link: absolute
  f_alacritty.yml:
    src: config/alacritty/alacritty.yml
    dst: ~/.config/alacritty/alacritty.yml
  f_alacritty-vifm.desktop:
    src: local/share/applications/alacritty-vifm.desktop
    dst: ~/.local/share/applications/alacritty-vifm.desktop
  f_bin_cargo-update-installed:
    src: bin/cargo-update-installed
    dst: ~/.local/bin/cargo-update-installed
  f_bin_dotdrop:
    src: bin/dotdrop
    dst: ~/.local/bin/dotdrop
  f_bin_pacdiff:
    src: bin/pacdiff
    dst: ~/.local/bin/pacdiff
  f_bin_power-menu:
    src: bin/power-menu
    dst: ~/.local/bin/power-menu
  f_bin_recompile-xmonad:
    src: bin/recompile-xmonad
    dst: ~/.local/bin/recompile-xmonad
  f_bin_toggle-touchpad:
    src: bin/toggle-touchpad
    dst: ~/.local/bin/toggle-touchpad
  f_bin_wifi-status:
    src: bin/wifi-status
    dst: ~/.local/bin/wifi-status
  f_config.fish:
    src: config/fish/config.fish
    dst: ~/.config/fish/config.fish
  f_dunstrc:
    src: config/dunst/dunstrc
    dst: ~/.config/dunst/dunstrc
  f_fish_theme:
    src: config/fish/conf.d/theme.fish
    dst: ~/.config/fish/conf.d/theme.fish
  f_git_config:
    src: config/git/config
    dst: ~/.config/git/config
  f_init.vim:
    src: config/nvim/init.vim
    dst: ~/.config/nvim/init.vim
    link: absolute
  f_profile:
    src: profile
    dst: ~/.profile
  f_redshift.conf:
    src: config/redshift.conf
    dst: ~/.config/redshift.conf
  f_ripgreprc:
    src: config/ripgreprc
    dst: ~/.config/ripgreprc
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  f_vifmrc:
    src: config/vifm/vifmrc
    dst: ~/.config/vifm/vifmrc
  f_vifm_colors:
    src: config/vifm/colors/Default-256-BoldStatus.vifm
    dst: ~/.config/vifm/colors/Default-256-BoldStatus.vifm
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xmobarrc:
    src: config/xmobar/xmobarrc
    dst: ~/.config/xmobar/xmobarrc
  f_xmonad.hs:
    src: config/xmonad/xmonad.hs
    dst: ~/.config/xmonad/xmonad.hs
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
profiles:
  home-desktop:
    dotfiles:
    - d_fish_functions_linux
    - d_spacemacs.d
    - f_alacritty.yml
    - f_alacritty-vifm.desktop
    - f_bin_cargo-update-installed
    - f_bin_dotdrop
    - f_bin_pacdiff
    - f_bin_power-menu
    - f_bin_recompile-xmonad
    - f_config.fish
    - f_dunstrc
    - f_fish_theme
    - f_git_config
    - f_init.vim
    - f_profile
    - f_redshift.conf
    - f_ripgreprc
    - f_ssh_config
    - f_vifmrc
    - f_vifm_colors
    - f_xinitrc
    - f_xmobarrc
    - f_xmonad.hs
  laptop:
    dotfiles:
    - d_fish_functions_linux
    - d_spacemacs.d
    - f_alacritty.yml
    - f_alacritty-vifm.desktop
    - f_bin_dotdrop
    - f_bin_pacdiff
    - f_bin_power-menu
    - f_bin_recompile-xmonad
    - f_bin_toggle-touchpad
    - f_bin_wifi-status
    - f_config.fish
    - f_dunstrc
    - f_fish_theme
    - f_git_config
    - f_init.vim
    - f_profile
    - f_redshift.conf
    - f_ripgreprc
    - f_ssh_config
    - f_vifmrc
    - f_vifm_colors
    - f_xinitrc
    - f_xmobarrc
    - f_xmonad.hs
  work-mac:
    dotfiles:
    - d_fish_functions_mac
    - d_spacemacs.d
    - f_bin_cargo-update-installed
    - f_bin_dotdrop
    - f_config.fish
    - f_fish_theme
    - f_git_config
    - f_init.vim
    - f_profile
    - f_ripgreprc
    - f_ssh_config
    - f_zshenv
