config:
  backup: true
  create: true
  dotpath: dotfiles
  minversion: 0.29.3
dotfiles:
  d_fish_functions:
    dst: ~/.config/fish/functions
    link: link
    src: config/fish/functions
  d_spacemacs.d:
    dst: ~/.spacemacs.d
    link: link
    src: spacemacs.d
  f_aurman_config:
    dst: ~/.config/aurman/aurman_config
    src: config/aurman/aurman_config
  f_bin_power-menu:
    src: bin/power-menu
    dst: ~/bin/power-menu
  f_bin_toggle-touchpad:
    dst: ~/bin/toggle-touchpad
    link: link
    src: bin/toggle-touchpad
  f_bin_volume:
    dst: ~/bin/volume
    link: link
    src: bin/volume
  f_config.fish:
    dst: ~/.config/fish/config.fish
    src: config/fish/config.fish
  f_dunstrc:
    dst: ~/.config/dunst/dunstrc
    src: config/dunst/dunstrc
  f_git_config:
    dst: ~/.config/git/config
    src: config/git/config
  f_init.vim:
    dst: ~/.config/nvim/init.vim
    link: link
    src: config/nvim/init.vim
  f_pacdiff-merge3:
    src: bin/pacdiff-merge3
    dst: ~/bin/pacdiff-merge3
  f_profile:
    dst: ~/.profile
    src: profile
  f_ssh_config:
    dst: ~/.ssh/config
    src: ssh/config
  f_xinitrc:
    dst: ~/.xinitrc
    src: xinitrc
  f_xmobar:
    dst: ~/.xmonad/xmobar
    src: xmonad/xmobar
  f_xmonad.hs:
    dst: ~/.xmonad/xmonad.hs
    src: xmonad/xmonad.hs
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  home-desktop:
    dotfiles:
    - d_fish_functions
    - d_spacemacs.d
    - f_aurman_config
    - f_bin_power-menu
    - f_bin_volume
    - f_config.fish
    - f_dunstrc
    - f_git_config
    - f_init.vim
    - f_pacdiff-merge3
    - f_profile
    - f_ssh_config
    - f_xinitrc
    - f_xmobar
    - f_xmonad.hs
    - f_xresources
  laptop:
    dotfiles:
    - d_fish_functions
    - d_spacemacs.d
    - f_aurman_config
    - f_bin_power-menu
    - f_bin_toggle-touchpad
    - f_config.fish
    - f_dunstrc
    - f_git_config
    - f_init.vim
    - f_pacdiff-merge3
    - f_profile
    - f_ssh_config
    - f_xinitrc
    - f_xmobar
    - f_xmonad.hs
    - f_xresources
