config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
profiles:
  home-desktop:
    dotfiles:
    - f_xresources
  laptop:
    dotfiles:
    - f_xresources
