[font]
size = 9.0

[font.offset]
y = -2

[font.normal]
family = "DejaVu Sans Mono"

[window.padding]
x = 2
y = 3

[colors.primary]
background = "#080808"
foreground = "#b2b2b2"

[colors.normal]
black = "#000000"
blue = "#0077ed"
cyan = "#00cdcd"
green = "#00cd00"
magenta = "#ea61da"
red = "#ee2c2c"
white = "#e5e5e5"
yellow = "#cdcd00"

[colors.bright]
black = "#7f7f7f"
blue = "#009cff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"
